### PR TITLE
Carlos Victoria assignment 3

### PR DESCRIPTION
**Pull request by Carlos0smar**

### CODE REVIEW

**Comment by Carlos0smar** [comment]
CheckStyle Main .-

Captura de pantalla (10)

Captura de pantalla (11)

CheckStyle Test .-

Captura de pantalla (12)

Captura de pantalla (13)

SonarLint .-

Captura de pantalla (14)

Captura de pantalla (15)

**Comment by marcos-x86** [comment]
|Overall Project|100%|:green_circle:|
|:-|:-|:-:|
|Files changed|100%|:green_circle:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[CollatzConjecture.java](https://github.com/SoftwareDevFundamentals/coding/blob/13142fb2c5796e622ff03a56c3f08efe40c2721f/src%2Fmain%2Fjava%2Fbo%2Fusfx%2FcarlosVictoria%2FCollatzConjecture.java)|100%|:green_circle:|
|[TotalPoints.java](https://github.com/SoftwareDevFundamentals/coding/blob/13142fb2c5796e622ff03a56c3f08efe40c2721f/src%2Fmain%2Fjava%2Fbo%2Fusfx%2FcarlosVictoria%2FTotalPoints.java)|100%|:green_circle:|

**Comment by marcos-x86** [comment]
|Overall Project|100%|:green_circle:|
|:-|:-|:-:|
|Files changed|100%|:green_circle:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[CollatzConjecture.java](https://github.com/SoftwareDevFundamentals/coding/blob/c995e54891cf4f65f6f19a23cff3cf52503c3640/src%2Fmain%2Fjava%2Fbo%2Fusfx%2FcarlosVictoria%2FCollatzConjecture.java)|100%|:green_circle:|
|[TotalPoints.java](https://github.com/SoftwareDevFundamentals/coding/blob/c995e54891cf4f65f6f19a23cff3cf52503c3640/src%2Fmain%2Fjava%2Fbo%2Fusfx%2FcarlosVictoria%2FTotalPoints.java)|100%|:green_circle:|
|[RowWeights.java](https://github.com/SoftwareDevFundamentals/coding/blob/c995e54891cf4f65f6f19a23cff3cf52503c3640/src%2Fmain%2Fjava%2Fbo%2Fusfx%2FcarlosVictoria%2FRowWeights.java)|100%|:green_circle:|

**Review by marcos-x86 — APPROVED** [review]
Great Job!

**Pull request merged**
